name = "Enriccraft"
author = "Eloimbot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dd89679fa1818e27a47dc2ebf15a4aa2c7504c1261f526c539f6d5e53770600"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
