name = "Enriccraft"
author = "Eloimbot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d71ffe35be9dafcb59965499d65196745bfa99182b3c399249da88765535fed"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
